name: CI
on: [push, pull_request]
env:
  _PEX_TEST_PYENV_ROOT: .pyenv_test
jobs:
  cpython-unit-tests:
    name: (${{ matrix.os }}) TOXENV=py${{ join(matrix.python-version, '') }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [[3, 6]]
        os: [windows-2019, ubuntu-20.04]
        exclude:
          - os: macos-10.15
            python-version: [3, 5]
          - os: macos-10.15
            python-version: [3, 6]
          - os: macos-10.15
            python-version: [3, 7]
          - os: macos-10.15
            python-version: [3, 8]
    steps:
      - name: Checkout Pex
        uses: actions/checkout@v2
      - name: Setup Python ${{ join(matrix.python-version, '.') }}
        uses: actions/setup-python@v2
        with:
          python-version: "${{ join(matrix.python-version, '.') }}"
      - name: Cache Pyenv Interpreters
        uses: actions/cache@v2
        with:
          path: ${{ env._PEX_TEST_PYENV_ROOT }}
          key: ${{ runner.os }}-pyenv-root
      - name: Run Unit Tests
        uses: ./.github/actions/run-tox
        with:
          tox-env: py${{ join(matrix.python-version, '') }}